version: "3"
services:
  app:
    image: strapi/strapi:alpine
    container_name: electromart-app
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PW}
      DATABASE_SSL: "false"
    volumes:
      - ./app:/srv/app
    ports:
      - "34001:1337"
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    container_name: electromart-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_USER: ${DB_USER}
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-stuff/mysql:/docker-entrypoint-initdb.d